# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
 name: Default

#variables:
#- group: TF_Varibales*/

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

#----------------------------------------------------------------------------------------------------
# Download & Install Terraform
#----------------------------------------------------------------------------------------------------

- script:
   
    terraform --version && df -kh && terraform init && terraform plan && terraform apply --auto-approve
